/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Brand — Deloitte-inspired palette
        ada: {
          green: '#86BC25',
          'green-light': '#9cd32c',
          'green-dark': '#6B9E1A',
          'green-glow': 'rgba(134,188,37,0.3)',
          blue: '#00A3E0',
          'blue-light': '#33B5E8',
          'blue-glow': 'rgba(0,163,224,0.3)',
          purple: '#8B5CF6',
          'purple-glow': 'rgba(139,92,246,0.3)',
        },
        // Surface hierarchy — mapped to CSS variables
        surface: {
          base: 'var(--surface-base)',
          DEFAULT: 'var(--surface-base)',
          elevated: 'var(--surface-elevated)',
          floating: 'var(--surface-floating)',
          card: 'var(--surface-card)',
          'card-hover': 'var(--surface-card-hover)',
          border: 'var(--surface-border)',
          'border-subtle': 'var(--surface-border-subtle)',
          'border-active': 'var(--surface-border-active)',
          modal: 'var(--surface-elevated)',
          overlay: 'var(--surface-overlay)',
          secondary: 'var(--surface-elevated)',
          terminal: 'var(--surface-terminal)',
          'glass': 'var(--surface-glass)',
          'glass-heavy': 'var(--surface-glass-heavy)',
        },
        // Text hierarchy — mapped to CSS variables
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          subtle: 'var(--text-subtle)',
          inverse: 'var(--text-inverse)',
          'glow': 'var(--text-glow)',
        },
        // Domain accent system
        discovery: {
          DEFAULT: '#86BC25',
          muted: 'rgba(134,188,37,0.12)',
          border: 'rgba(134,188,37,0.25)',
          glow: 'rgba(134,188,37,0.4)',
        },
        knowledge: {
          DEFAULT: '#00A3E0',
          muted: 'rgba(0,163,224,0.12)',
          border: 'rgba(0,163,224,0.25)',
          glow: 'rgba(0,163,224,0.4)',
        },
        infra: {
          DEFAULT: '#8B5CF6',
          muted: 'rgba(139,92,246,0.12)',
          border: 'rgba(139,92,246,0.25)',
          glow: 'rgba(139,92,246,0.4)',
        },
        security: {
          DEFAULT: '#EF4444',
          muted: 'rgba(239,68,68,0.12)',
          border: 'rgba(239,68,68,0.25)',
          medium: '#F59E0B',
          low: '#10B981',
        },
        telemetry: {
          DEFAULT: '#F59E0B',
          muted: 'rgba(245,158,11,0.12)',
          border: 'rgba(245,158,11,0.25)',
        },
        reports: {
          DEFAULT: '#EC4899',
          muted: 'rgba(236,72,153,0.12)',
          border: 'rgba(236,72,153,0.25)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['3.5rem', { lineHeight: '1.08', letterSpacing: '-0.03em', fontWeight: '700' }],
        heading: ['2rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        title: ['1.25rem', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        body: ['0.9375rem', { lineHeight: '1.6', fontWeight: '400' }],
        caption: ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
        metadata: ['0.6875rem', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.04em' }],
        code: ['0.875rem', { lineHeight: '1.6', fontWeight: '400' }],
        'code-sm': ['0.6875rem', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        30: '7.5rem',
        34: '8.5rem',
        38: '9.5rem',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite alternate',
        'fade-in': 'fadeIn 0.4s ease-out',
        'scale-in': 'scaleIn 0.35s cubic-bezier(0.16,1,0.3,1)',
        'slide-up': 'slideUp 0.45s cubic-bezier(0.16,1,0.3,1)',
        'slide-down': 'slideDown 0.45s cubic-bezier(0.16,1,0.3,1)',
        shimmer: 'shimmer 2s linear infinite',
        'border-glow': 'borderGlow 2s ease-in-out infinite alternate',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'spin-slow': 'spin 12s linear infinite',
        'bounce-subtle': 'bounceSubtle 2s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'node-enter': 'nodeEnter 0.5s cubic-bezier(0.16,1,0.3,1) forwards',
        'node-complete': 'nodeComplete 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'progress-fill': 'progressFill 0.6s ease-out forwards',
        'ambient-drift': 'ambientDrift 20s ease-in-out infinite alternate',
        'ambient-drift-2': 'ambientDrift2 25s ease-in-out infinite alternate',
        'check-draw': 'checkDraw 0.4s ease-out forwards',
        'particle-float': 'particleFloat 15s linear infinite',
        'scan-line': 'scanLine 3s linear infinite',
        'data-stream': 'dataStream 2s linear infinite',
        'morph-blob': 'morphBlob 8s ease-in-out infinite',
        'grid-pulse': 'gridPulse 4s ease-in-out infinite',
        'typing': 'typing 3.5s steps(40, end)',
        'blink': 'blink 1s step-end infinite',
        'orbit': 'orbit 20s linear infinite',
        'orbit-reverse': 'orbit 25s linear infinite reverse',
        'wave': 'wave 2s ease-in-out infinite',
        'ripple': 'ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        borderGlow: {
          '0%': { boxShadow: '0 0 0 0 rgba(134,188,37,0)' },
          '100%': { boxShadow: '0 0 20px 2px rgba(134,188,37,0.12)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(134,188,37,0.3), inset 0 0 0 1px rgba(134,188,37,0.3)' },
          '50%': { boxShadow: '0 0 16px 4px rgba(134,188,37,0.15), inset 0 0 0 1px rgba(134,188,37,0.5)' },
        },
        nodeEnter: {
          '0%': { opacity: '0', transform: 'scale(0.8) translateY(8px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        nodeComplete: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.08)' },
          '100%': { transform: 'scale(1)' },
        },
        progressFill: {
          '0%': { width: '0%' },
          '100%': { width: 'var(--progress)' },
        },
        ambientDrift: {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '100%': { transform: 'translate(60px, -40px) scale(1.1)' },
        },
        ambientDrift2: {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '100%': { transform: 'translate(-80px, 50px) scale(1.05)' },
        },
        checkDraw: {
          '0%': { strokeDashoffset: '24' },
          '100%': { strokeDashoffset: '0' },
        },
        particleFloat: {
          '0%': { transform: 'translateY(100vh) scale(0)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(-100vh) scale(1)', opacity: '0' },
        },
        scanLine: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        dataStream: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        morphBlob: {
          '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '25%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
          '50%': { borderRadius: '50% 60% 30% 60% / 30% 40% 70% 60%' },
          '75%': { borderRadius: '60% 40% 60% 30% / 70% 30% 50% 60%' },
        },
        gridPulse: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.6' },
        },
        typing: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        orbit: {
          '0%': { transform: 'rotate(0deg) translateX(120px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(120px) rotate(-360deg)' },
        },
        wave: {
          '0%, 100%': { transform: 'scaleY(1)' },
          '50%': { transform: 'scaleY(0.5)' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'glow-green': '0 0 20px rgba(134,188,37,0.2)',
        'glow-green-lg': '0 0 40px rgba(134,188,37,0.3)',
        'glow-blue': '0 0 20px rgba(0,163,224,0.2)',
        'glow-purple': '0 0 20px rgba(139,92,246,0.2)',
        'glow-green-sm': '0 0 8px rgba(134,188,37,0.25)',
        'panel': '0 4px 24px rgba(0,0,0,0.4)',
        'card': '0 2px 12px rgba(0,0,0,0.3)',
        'neo': '0 1px 2px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.04)',
        'modal': '0 32px 64px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.05)',
        'glass': '0 8px 32px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.05)',
        'inner-glow': 'inset 0 0 20px rgba(134,188,37,0.1)',
        'neon': '0 0 5px rgba(134,188,37,0.5), 0 0 20px rgba(134,188,37,0.3), 0 0 40px rgba(134,188,37,0.1)',
      },
    },
  },
  plugins: [],
}